
//Matematiksel işlemler 

// console.log(2 + 3) 
// console.log(3 - 2) 
// console.log(2 * 3) 
// console.log(3 / 2) 
// console.log(3 % 2) 
// console.log(3 ** 2) 

// Veri  tipi kontrolüs

// console.log(typeof 'Osman') 
// console.log(typeof 5) 
// console.log(typeof true) 
// console.log(typeof null) 
// console.log(typeof undefined)

//Değişken tanımlama 

// let firstName = 'Alptuğ' 
// let lastName = 'Ulus' 
// let country = 'Türkiye' 
// let city = 'İstanbul' 
// let age = 26 
// let isMarried = false

// console.log(firstName, lastName, country, city, age, isMarried)


// const gravity = 9.81 
// const boilingPoint = 100 
// const PI = 3.14 
// console.log(gravity, boilingPoint, PI)


// let name = 'Jhon', job = 'teacher', live = 'Turkey'
// console.log(name, job, live)



// Primitive Data Types (İlkel veri  tipleri)

// 1)Numbers - Integers, floats
// 2)Strings - Any data under single quote, double quote or backtick quote
// 3)Booleans - true or false value
// 4)Null - empty value or no value
// 5)Undefined - a declared variable without a value
// 6)Symbol - A unique value that can be generated by Symbol constructor

//karşılaştırma

// let numOne = 3
// let numTwo = 3333333333

// console.log(numOne == numTwo)     
// let js = 'JavaScript'
// let py = 'Python'

// console.log(js == py)           

// let lightOn = true
// let lightOff = false

// console.log(lightOn == lightOff)

// // Non-Primitive Data Types 
// 1) Objects
// 2) Arrays

// let nums = [1, 2, 3,]
// nums[0] = 10

// let person = {
//  name : 'Muhammet ',
//  surname : 'Varol',
//  age : '27',

// }
// console.log(person)
// console.log(person.age)

// console.log(nums)  


// Math. kullanımı 
// const PI = Math.PI

// console.log(PI)                          

// console.log(Math.round(PI))                

// console.log(Math.round(9.81))    

// console.log(Math.floor(PI))               

// console.log(Math.ceil(PI))                 

// console.log(Math.min(-5, 3, 20, 4, 5, 10))  
// console.log(Math.max(-5, 3, 20, 4, 5, 10)) 

// const randNum = Math.random() 
// console.log(randNum)

// const num = Math.floor(Math.random () * 11) // creates random number between 0 and 10
// console.log(num)

// //Absolute value
// console.log(Math.abs(-10)) 

// //Square root
// console.log(Math.sqrt(100))    

// console.log(Math.sqrt(2))      

// // Power
// console.log(Math.pow(3, 2))    // console.log(3**2)
// console.log(Math.E)             

// // Logarithm
// // Returns the natural logarithm with base E of x, Math.log(x)
// console.log(Math.log(2))       
// console.log(Math.log(10))       

// // Returns the natural logarithm of 2 and 10 respectively

// console.log(Math.LN2)           
// console.log(Math.LN10)          

// // Trigonometry
// Math.sin(0)
// Math.sin(60)

// Math.cos(0)
// Math.cos(60)

//String Concatenation

let space = ' '
let firstName = 'Asabeneh'
let lastName = 'Yetayeh'
let country = 'Finland'
let city = 'Helsinki'
let language = 'JavaScript'
let job = 'teacher'
let age = 250


// // let fullName =firstName + space + lastName
// let personInfoOne = firstName + '. I am ' + age + '. I live in '  " " + country; // ES5 string addition

//  console.log(personInfoOne)
// let trueExample = `${firstName}  I am ${age} I live in ${country }` 
//  console.log(trueExample)

// console.log(personInfoOne)

// let numOne = 4
// let numTwo = 3
// let sum = numOne + numTwo
// let diff = numOne - numTwo
// let mult = numOne * numTwo
// let div = numOne / numTwo
// let remainder = numOne % numTwo
// let powerOf = numOne ** numTwo

// console.log(sum, diff, mult, div, remainder, powerOf) 


//Comparison Operators

// console.log(3 > 2)              
// console.log(3 >= 2)             
// console.log(3 < 2)             
// console.log(2 < 3)              
// console.log(2 <= 3)             
// console.log(3 == 2)             
// console.log(3 != 2)             
// console.log(3 == '3')           
// console.log(3 === '3')         
// console.log(3 !== '3')          
// console.log(3 != 3)            
// console.log(3 !== 3)           
// console.log(0 == false)         
// console.log(0 === false)       
// console.log(0 == '')            
// console.log(0 == ' ')           
// console.log(0 === '')           
// console.log(1 == true)         
// console.log(1 === true)         
// console.log(null == null) 
// console.log(undefined === null) 
// console.log(NaN == NaN)         
// console.log(NaN === NaN)        
// console.log(typeof NaN)         

// console.log('mango'.length == 'avocado'.length)  
// console.log('mango'.length != 'avocado'.length)  
// console.log('mango'.length < 'avocado'.length)   
// console.log('milk'.length == 'meat'.length)      
// console.log('milk'.length != 'meat'.length)      
// console.log('tomato'.length == 'potato'.length)  
// console.log('python'.length > 'dragon'.length)   


//Logical Operators

// && ampersand operator 

// const check1 = 4 > 3 && 10 > 5 ; 
// const check2 = 4 > 3 && 10 < 5 ;    
// const check3 = 4 < 3 && 10 < 5 ;   

// console.log(check1,check2,check3)


// || pipe or operator 

// const check4 = 4 > 3 || 10 > 5       
// const check5 = 4 > 3 || 10 < 5        
// const check6 = 4 < 3 || 10 < 5  

// console.log(check6,check5,check4)

//Pre-increment

// let count = 0
// console.log(++count)        
// console.log(count)          

//Post-increment

// let count = 0
// console.log(count--)       
// console.log(count)  

//Window prompt() method

// let number = prompt('Enter number', 'number goes here')
// console.log(number)


// Window confirm() method

// const agree = confirm('Are you sure you like to delete? ')
// console.log(agree) 


//Date Object

// const now = new Date() 
// console.log(now.getTime())

// const allSeconds = Date.now() 
// console.log(allSeconds) 

// const timeInSeconds = new Date().getTime()
// console.log(allSeconds == timeInSeconds) 

// const year = now.getFullYear() 
// const month = now.getMonth() + 1  
// const date = now.getDate() 
// const hours = now.getHours() 
// const minutes = now.getMinutes() 

// console.log(`${date}/${month}/${year} ${hours}:${minutes}`) 

//Ternary Operators

// let isRaining = true
// isRaining
//   ? console.log('You need a rain coat.')
//   : console.log('No need for a rain coat.')
// isRaining = false

// isRaining
//   ? console.log('You need a rain coat.')
//   : console.log('No need for a rain coat.')


// If Else
// if (condition) {
//     // this part of code runs for truthy condition
//   } else {
//     // this part of code runs for false condition
//   }

// let num = -3
// if (num > 0) {
//   console.log(`${num} is a positive number`)
// } else {
//   console.log(`${num} is a negative number`)
// }


// num = -3
// if (num > 0) {
//   console.log(`${num} is a positive number`)
// } else {
//   console.log(`${num} is a negative number`)
// }


// If Else if Else

// let a = 0
// if (a > 0) {
//   console.log(`${a} is a positive number`)
// } else if (a < 0) {
//   console.log(`${a} is a negative number`)
// } else if (a == 0) {
//   console.log(`${a} is zero`)
// } else {
//   console.log(`${a} is not a number`)
// }

// switch(caseValue){
//     case 1:
//       // code
//       break
//     case 2:
//      // code
//      break
//     case 3:
//      // code
//      break
//     default:
//      // code
//   }

let dayUserInput = prompt('What day is today ?')
let day = dayUserInput.toLowerCase()

switch (day) {
  case 'monday':
    console.log('Today is Monday')
     break
  case 'tuesday':
    console.log('Today is Tuesday')
    break
  case 'wednesday':
    console.log('Today is Wednesday')
    break
  case 'thursday':
    console.log('Today is Thursday')
    break
  case 'friday':
    console.log('Today is Friday')
    break
  case 'saturday':
    console.log('Today is Saturday')
    break
  case 'sunday':
    console.log('Today is Sunday')
    break
  default:
    console.log('It is not a week day.')
}