// //Matematiksel işlemler

// // console.log(2 + 3)
// // console.log(3 - 2)
// // console.log(2 * 3)
// // console.log(3 / 2)
// // console.log(3 % 2)
// // console.log(3 ** 2)

// // Veri  tipi kontrolüs

// // console.log(typeof 'Osman')
// // console.log(typeof 5)
// // console.log(typeof true)
// // console.log(typeof null)
// // console.log(typeof undefined)

// //Değişken tanımlama

// // let firstName = 'Alptuğ'
// // let lastName = 'Ulus'
// // let country = 'Türkiye'
// // let city = 'İstanbul'
// // let age = 26
// // let isMarried = false

// // console.log(firstName, lastName, country, city, age, isMarried)

// // const gravity = 9.81
// // const boilingPoint = 100
// // const PI = 3.14
// // console.log(gravity, boilingPoint, PI)

// // let name = 'Jhon', job = 'teacher', live = 'Turkey'
// // console.log(name, job, live)

// // Primitive Data Types (İlkel veri  tipleri)

// // 1)Numbers - Integers, floats
// // 2)Strings - Any data under single quote, double quote or backtick quote
// // 3)Booleans - true or false value
// // 4)Null - empty value or no value
// // 5)Undefined - a declared variable without a value
// // 6)Symbol - A unique value that can be generated by Symbol constructor

// //karşılaştırma

// // let numOne = 3
// // let numTwo = 3333333333

// // console.log(numOne == numTwo)
// // let js = 'JavaScript'
// // let py = 'Python'

// // console.log(js == py)

// // let lightOn = true
// // let lightOff = false

// // console.log(lightOn == lightOff)

// // // Non-Primitive Data Types
// // 1) Objects
// // 2) Arrays

// // let nums = [1, 2, 3,]
// // nums[0] = 10

// // let person = {
// //  name : 'Muhammet ',
// //  surname : 'Varol',
// //  age : '27',

// // }
// // console.log(person)
// // console.log(person.age)

// // console.log(nums)

// // Math. kullanımı
// // const PI = Math.PI

// // console.log(PI)

// // console.log(Math.round(PI))

// // console.log(Math.round(9.81))

// // console.log(Math.floor(PI))

// // console.log(Math.ceil(PI))

// // console.log(Math.min(-5, 3, 20, 4, 5, 10))
// // console.log(Math.max(-5, 3, 20, 4, 5, 10))

// // const randNum = Math.random()
// // console.log(randNum)

// // const num = Math.floor(Math.random () * 11) // creates random number between 0 and 10
// // console.log(num)

// // //Absolute value
// // console.log(Math.abs(-10))

// // //Square root
// // console.log(Math.sqrt(100))

// // console.log(Math.sqrt(2))

// // // Power
// // console.log(Math.pow(3, 2))    // console.log(3**2)
// // console.log(Math.E)

// // // Logarithm
// // // Returns the natural logarithm with base E of x, Math.log(x)
// // console.log(Math.log(2))
// // console.log(Math.log(10))

// // // Returns the natural logarithm of 2 and 10 respectively

// // console.log(Math.LN2)
// // console.log(Math.LN10)

// // // Trigonometry
// // Math.sin(0)
// // Math.sin(60)

// // Math.cos(0)
// // Math.cos(60)

// //String Concatenation

// // let space = ' '
// // let firstName = 'Asabeneh'
// // let lastName = 'Yetayeh'
// // let country = 'Finland'
// // let city = 'Helsinki'
// // let language = 'JavaScript'
// // let job = 'teacher'
// // let age = 250

// // // let fullName =firstName + space + lastName
// // let personInfoOne = firstName + '. I am ' + age + '. I live in '  " " + country; // ES5 string addition

// //  console.log(personInfoOne)
// // let trueExample = `${firstName}  I am ${age} I live in ${country }`
// //  console.log(trueExample)

// // console.log(personInfoOne)

// // let numOne = 4
// // let numTwo = 3
// // let sum = numOne + numTwo
// // let diff = numOne - numTwo
// // let mult = numOne * numTwo
// // let div = numOne / numTwo
// // let remainder = numOne % numTwo
// // let powerOf = numOne ** numTwo

// // console.log(sum, diff, mult, div, remainder, powerOf)

// //Comparison Operators

// // console.log(3 > 2)
// // console.log(3 >= 2)
// // console.log(3 < 2)
// // console.log(2 < 3)
// // console.log(2 <= 3)
// // console.log(3 == 2)
// // console.log(3 != 2)
// // console.log(3 == '3')
// // console.log(3 === '3')
// // console.log(3 !== '3')
// // console.log(3 != 3)
// // console.log(3 !== 3)
// // console.log(0 == false)
// // console.log(0 === false)
// // console.log(0 == '')
// // console.log(0 == ' ')
// // console.log(0 === '')
// // console.log(1 == true)
// // console.log(1 === true)
// // console.log(null == null)
// // console.log(undefined === null)
// // console.log(NaN == NaN)
// // console.log(NaN === NaN)
// // console.log(typeof NaN)

// // console.log('mango'.length == 'avocado'.length)
// // console.log('mango'.length != 'avocado'.length)
// // console.log('mango'.length < 'avocado'.length)
// // console.log('milk'.length == 'meat'.length)
// // console.log('milk'.length != 'meat'.length)
// // console.log('tomato'.length == 'potato'.length)
// // console.log('python'.length > 'dragon'.length)

// //Logical Operators

// // && ampersand operator

// // const check1 = 4 > 3 && 10 > 5 ;
// // const check2 = 4 > 3 && 10 < 5 ;
// // const check3 = 4 < 3 && 10 < 5 ;

// // console.log(check1,check2,check3)

// // || pipe or operator

// // const check4 = 4 > 3 || 10 > 5
// // const check5 = 4 > 3 || 10 < 5
// // const check6 = 4 < 3 || 10 < 5

// // console.log(check6,check5,check4)

// //Pre-increment

// // let count = 0
// // console.log(++count)
// // console.log(count)

// //Post-increment

// // let count = 0
// // console.log(count--)
// // console.log(count)

// //Window prompt() method

// // let number = prompt('Enter number', 'number goes here')
// // console.log(number)

// // Window confirm() method

// // const agree = confirm('Are you sure you like to delete? ')
// // console.log(agree)

// //Date Object

// // const now = new Date()
// // console.log(now.getTime())

// // const allSeconds = Date.now()
// // console.log(allSeconds)

// // const timeInSeconds = new Date().getTime()
// // console.log(allSeconds == timeInSeconds)

// // const year = now.getFullYear()
// // const month = now.getMonth() + 1
// // const date = now.getDate()
// // const hours = now.getHours()
// // const minutes = now.getMinutes()

// // console.log(`${date}/${month}/${year} ${hours}:${minutes}`)

// //Ternary Operators

// // let isRaining = true
// // isRaining
// //   ? console.log('You need a rain coat.')
// //   : console.log('No need for a rain coat.')
// // isRaining = false

// // isRaining
// //   ? console.log('You need a rain coat.')
// //   : console.log('No need for a rain coat.')

// // If Else
// // if (condition) {
// //     // this part of code runs for truthy condition
// //   } else {
// //     // this part of code runs for false condition
// //   }

// // let num = -3
// // if (num > 0) {
// //   console.log(`${num} is a positive number`)
// // } else {
// //   console.log(`${num} is a negative number`)
// // }

// // num = -3
// // if (num > 0) {
// //   console.log(`${num} is a positive number`)
// // } else {
// //   console.log(`${num} is a negative number`)
// // }

// // If Else if Else

// // let a = 0
// // if (a > 0) {
// //   console.log(`${a} is a positive number`)
// // } else if (a < 0) {
// //   console.log(`${a} is a negative number`)
// // } else if (a == 0) {
// //   console.log(`${a} is zero`)
// // } else {
// //   console.log(`${a} is not a number`)
// // }

// // switch(caseValue){
// //     case 1:
// //       // code
// //       break
// //     case 2:
// //      // code
// //      break
// //     case 3:
// //      // code
// //      break
// //     default:
// //      // code
// //   }

// // let dayUserInput = prompt('What day is today ?')
// // let day = dayUserInput.toLowerCase()

// // switch (day) {
// //   case 'monday':
// //     console.log('Today is Monday')
// //      break
// //   case 'tuesday':
// //     console.log('Today is Tuesday')
// //     break
// //   case 'wednesday':
// //     console.log('Today is Wednesday')
// //     break
// //   case 'thursday':
// //     console.log('Today is Thursday')
// //     break
// //   case 'friday':
// //     console.log('Today is Friday')
// //     break
// //   case 'saturday':
// //     console.log('Today is Saturday')
// //     break
// //   case 'sunday':
// //     console.log('Today is Sunday')
// //     break
// //   default:
// //     console.log('It is not a week day.')
// // }

// // const person = {
// //     firstName: 'Asabeneh',
// //     lastName: 'Yetayeh',
// //     age: 250,
// //     country: 'Finland',
// //     city: 'Helsinki',
// //     skills: [
// //       'HTML',
// //       'CSS',
// //       'JavaScript',
// //       'React',
// //       'Node',
// //       'MongoDB',
// //       'Python',
// //       'D3.js'
// //     ],
// //     getFullName: function() {
// //       return `${this.firstName} ${this.lastName}`
// //     }
// //   }
// //   person.nationality = 'Ethiopian'
// //   person.country = 'Finland'
// //   person.title = 'teacher'
// //   person.skills.push('Meteor')
// //   person.skills.push('SasS')
// //   person.isMarried = true

// //   person.getPersonInfo = function() {
// //     let skillsWithoutLastSkill = this.skills
// //       .splice(0, this.skills.length - 1)
// //       .join(', ')
// //     let lastSkill = this.skills.splice(this.skills.length - 1)[0]

// //     let skills = `${skillsWithoutLastSkill}, and ${lastSkill}`
// //     let fullName = this.getFullName()
// //     let statement = `${fullName} is a ${this.title}.\nHe lives in ${this.country}.\nHe teaches ${skills}.`
// //     return statement
// //   }
// //   console.log(person)
// //   console.log(person.getPersonInfo())

///////////////////////////////////////////////////////////////////////////////Functions/////////////////////////////////////////////////////////////////////////////////

//declaring a function without a parameter
// function functionName() {
//   // code goes here
// }
// functionName()// calling function by its name and with parentheses

// function square() {
//   let num = 2
//   let sq = num * num
//   console.log(sq)
// }

// square()

// function printFullName (){
//   let firstName = 'Alptuğ'
//   let lastName = 'Ulus'
//   let fullName = `${firstName} ${lastName}`
//   console.log(fullName)
// }

// printFullName()

// function sumAllNums() {
//   let sum = 0;
//   for (let i = 0; i < arguments.length; i++) {
//     sum += arguments[i]
//   }
//   return sum
// }

// console.log(sumAllNums(1, 2, 3, 4))
// console.log(sumAllNums(10, 20, 13, 40, 10))
// console.log(sumAllNums(15, 20, 30, 25, 10, 33, 40))

// function sumTwoNumbers(numOne, numTwo) {
//   let sum = numOne + numTwo
//   return sum
// }

// console.log(sumTwoNumbers(10,20))

// function sumArrayValues(arr) {
//   let sum = 0;
//   for (let i = 0; i < arr.length; i++) {
//     sum = sum + arr[i];
//   }
//   return sum;
// }
// const numbers = [1, 2, 3, 4, 5];
//     //calling a function
// console.log(sumArrayValues(numbers));

// function greetings(name = 'Alptuğ') {
//   let message = `${name},!`
//   return message
// }

// console.log(greetings())
// console.log(greetings('Ali'))

////////////////////////////////////////////////////Functional Programming/////////////////////////////////////////////////////////////////////////////////////////////

let data = [
  {
    _id: "5e652aa6baec2fe6fea7ed2c",
    index: 0,
    guid: "25743f49-50b9-417a-93c3-12bb3f80514c",
    isActive: true,
    balance: "$2,339.94",
    picture: "http://placehold.it/32x32",
    age: 37,
    eyeColor: "blue",
    name: "Pate Henry",
    gender: "male",
    company: "MEDCOM",
    email: "patehenry@medcom.com",
    phone: "+1 (904) 587-2879",
    address: "937 Voorhies Avenue, Valle, Minnesota, 9831",
    about:
      "Aute aute ipsum veniam Lorem aliqua exercitation pariatur ullamco. Cupidatat nisi amet pariatur culpa nulla ipsum laborum adipisicing adipisicing anim enim dolore eu ut. Duis adipisicing nulla aliqua minim culpa voluptate.\r\n",
    registered: "2020-01-31T08:07:48 -03:00",
    latitude: 38.253873,
    longitude: -120.599697,
    tags: [
      "duis",
      "nulla",
      "deserunt",
      "nulla",
      "consectetur",
      "amet",
      "eiusmod",
    ],
    friends: [
      {
        id: 0,
        name: "Meagan Ray",
      },
      {
        id: 1,
        name: "Salas Macdonald",
      },
      {
        id: 2,
        name: "Diaz Gill",
      },
    ],
  },
  {
    _id: "5e652aa69cb94a55a21dbd24",
    index: 1,
    guid: "7fbd5a0a-5d8b-4cdd-97b7-f7715183ea60",
    isActive: true,
    balance: "$3,929.51",
    picture: "http://placehold.it/32x32",
    age: 30,
    eyeColor: "brown",
    name: "Carole Daniels",
    gender: "female",
    company: "EARTHPLEX",
    email: "caroledaniels@earthplex.com",
    phone: "+1 (863) 523-3588",
    address: "646 Montague Street, Cutter, Hawaii, 1870",
    about:
      "Eiusmod do qui veniam cupidatat velit est sit tempor nostrud nostrud tempor magna. Et officia velit excepteur dolor adipisicing adipisicing cupidatat voluptate et exercitation. Sint magna sit nisi laborum sunt dolore velit irure in proident. Veniam dolore amet amet dolor ullamco cupidatat Lorem.\r\n",
    registered: "2016-10-22T04:13:14 -03:00",
    latitude: 59.036927,
    longitude: 91.043976,
    tags: ["consectetur", "ut", "laboris", "officia", "velit", "in", "in"],
    friends: [
      {
        id: 0,
        name: "Payne Santana",
      },
      {
        id: 1,
        name: "Klein Woods",
      },
      {
        id: 2,
        name: "Beck Mosley",
      },
    ],
  },
  {
    _id: "5e652aa6c092ae931fa4ffab",
    index: 2,
    guid: "01c5f38f-42d6-4731-9b39-64a2d007fa77",
    isActive: false,
    balance: "$3,956.59",
    picture: "http://placehold.it/32x32",
    age: 26,
    eyeColor: "blue",
    name: "Rowe Prince",
    gender: "male",
    company: "ECOLIGHT",
    email: "roweprince@ecolight.com",
    phone: "+1 (969) 460-2384",
    address: "545 Hendrickson Place, Wikieup, Michigan, 9186",
    about:
      "Et do commodo do veniam labore velit qui do do pariatur aliqua excepteur laborum do. Velit sunt ad irure sit voluptate do. Voluptate cupidatat ex deserunt sit proident tempor ad et adipisicing deserunt esse voluptate dolore. Pariatur reprehenderit exercitation magna dolore labore voluptate laborum dolor. Veniam nostrud magna cupidatat esse consectetur.\r\n",
    registered: "2016-02-24T11:19:06 -02:00",
    latitude: 39.162822,
    longitude: -137.669166,
    tags: ["deserunt", "amet", "fugiat", "voluptate", "et", "ex", "quis"],
    friends: [
      {
        id: 0,
        name: "Allison Bailey",
      },
      {
        id: 1,
        name: "Jessica Holland",
      },
      {
        id: 2,
        name: "Battle Hood",
      },
    ],
  },
  {
    _id: "5e652aa642281be3552ea326",
    index: 3,
    guid: "65e32ce6-4407-4226-b0ef-ed9823042b06",
    isActive: false,
    balance: "$3,701.25",
    picture: "http://placehold.it/32x32",
    age: 33,
    eyeColor: "brown",
    name: "Tucker Snider",
    gender: "male",
    company: "YOGASM",
    email: "tuckersnider@yogasm.com",
    phone: "+1 (834) 501-3046",
    address: "686 Seba Avenue, Datil, New Mexico, 3966",
    about:
      "Duis enim Lorem elit enim laborum labore ullamco magna. Esse et sunt sint veniam cillum Lorem consequat et officia officia duis Lorem aute. Eiusmod minim labore do Lorem incididunt laboris ex esse velit commodo sit magna ea officia.\r\n",
    registered: "2020-02-03T10:32:02 -03:00",
    latitude: 20.177993,
    longitude: -160.148589,
    tags: ["veniam", "cillum", "nisi", "reprehenderit", "ex", "quis", "in"],
    friends: [
      {
        id: 0,
        name: "Ingram Phelps",
      },
      {
        id: 1,
        name: "Allie Thomas",
      },
      {
        id: 2,
        name: "Lorrie Kennedy",
      },
    ],
  },
  {
    _id: "5e652aa66ccf1a70ee6fb8cb",
    index: 4,
    guid: "d751f5e0-9ad0-4f29-98fa-68e3f6cc1caf",
    isActive: true,
    balance: "$2,990.40",
    picture: "http://placehold.it/32x32",
    age: 31,
    eyeColor: "green",
    name: "Sandoval Mercado",
    gender: "male",
    company: "TINGLES",
    email: "sandovalmercado@tingles.com",
    phone: "+1 (898) 449-3939",
    address: "451 Tompkins Avenue, Forbestown, Oregon, 9955",
    about:
      "Labore nostrud minim cillum commodo incididunt excepteur aute enim. Ullamco esse ad aliquip excepteur officia duis aliqua sunt. Cupidatat fugiat minim incididunt incididunt excepteur qui excepteur tempor in voluptate. Deserunt occaecat nostrud nulla ut ipsum do ea. Anim veniam eu enim dolor commodo laboris cillum duis sit consectetur ex voluptate.\r\n",
    registered: "2017-05-01T02:45:08 -03:00",
    latitude: 14.77,
    longitude: -53.926338,
    tags: [
      "amet",
      "deserunt",
      "laborum",
      "esse",
      "pariatur",
      "tempor",
      "minim",
    ],
    friends: [
      {
        id: 0,
        name: "Alexis Woodward",
      },
      {
        id: 1,
        name: "Dale Maldonado",
      },
      {
        id: 2,
        name: "Weiss Kramer",
      },
    ],
  },
  {
    _id: "5e652aa66b1b7adeed43cf53",
    index: 5,
    guid: "5c80de7e-c802-4ed0-9647-f0320120f574",
    isActive: true,
    balance: "$1,648.13",
    picture: "http://placehold.it/32x32",
    age: 39,
    eyeColor: "brown",
    name: "Michael Blair",
    gender: "male",
    company: "RONELON",
    email: "michaelblair@ronelon.com",
    phone: "+1 (870) 558-2079",
    address: "918 Gates Avenue, Lafferty, Rhode Island, 7400",
    about:
      "Qui dolor anim mollit pariatur do. Adipisicing elit et nostrud nostrud do do sit dolore anim commodo. Nulla excepteur reprehenderit ullamco commodo elit ad nulla. Veniam exercitation veniam nostrud irure proident consectetur velit.\r\n",
    registered: "2019-10-09T01:40:31 -03:00",
    latitude: 6.70974,
    longitude: -17.935264,
    tags: ["eu", "exercitation", "qui", "laboris", "cupidatat", "velit", "ex"],
    friends: [
      {
        id: 0,
        name: "Jody Day",
      },
      {
        id: 1,
        name: "Verna Fitzgerald",
      },
      {
        id: 2,
        name: "Kelsey Bryan",
      },
    ],
  },
  {
    _id: "5e652aa67ddb72a4446fbbde",
    index: 6,
    guid: "1f5ec923-a814-4668-915f-b5de223d3b82",
    isActive: true,
    balance: "$3,210.17",
    picture: "http://placehold.it/32x32",
    age: 29,
    eyeColor: "blue",
    name: "Day Weber",
    gender: "male",
    company: "ZILIDIUM",
    email: "dayweber@zilidium.com",
    phone: "+1 (875) 525-3161",
    address: "316 India Street, Yogaville, Oklahoma, 637",
    about:
      "Cillum minim deserunt laborum amet. Duis quis Lorem dolore anim deserunt non officia mollit nostrud minim. Non duis culpa fugiat nisi veniam quis nulla eu cillum nulla aliquip. Voluptate elit ipsum sit proident culpa aliquip irure commodo exercitation est cillum commodo elit.\r\n",
    registered: "2019-11-26T08:40:54 -03:00",
    latitude: 78.198523,
    longitude: 170.199633,
    tags: [
      "non",
      "reprehenderit",
      "et",
      "labore",
      "enim",
      "consectetur",
      "laborum",
    ],
    friends: [
      {
        id: 0,
        name: "Tanya Hickman",
      },
      {
        id: 1,
        name: "Lizzie Puckett",
      },
      {
        id: 2,
        name: "Mckenzie Donovan",
      },
    ],
  },
  {
    _id: "5e652aa646874bac9a75aea8",
    index: 7,
    guid: "28789d4d-0e1a-4237-9471-5fadd2a13210",
    isActive: false,
    balance: "$2,780.67",
    picture: "http://placehold.it/32x32",
    age: 32,
    eyeColor: "green",
    name: "Sharron Hendricks",
    gender: "female",
    company: "ENDIPIN",
    email: "sharronhendricks@endipin.com",
    phone: "+1 (909) 435-2017",
    address: "618 Cadman Plaza, Thermal, North Carolina, 8559",
    about:
      "Reprehenderit ipsum et eu minim id culpa cupidatat cillum ut veniam ut. Tempor sunt anim do voluptate officia. Elit ea culpa eu qui quis consequat sint anim sit voluptate amet.\r\n",
    registered: "2018-07-06T12:34:04 -03:00",
    latitude: 13.525033,
    longitude: -55.135384,
    tags: ["ea", "ut", "sunt", "adipisicing", "cupidatat", "tempor", "tempor"],
    friends: [
      {
        id: 0,
        name: "Snider Hopkins",
      },
      {
        id: 1,
        name: "Roxanne Ford",
      },
      {
        id: 2,
        name: "Wong Keith",
      },
    ],
  },
  {
    _id: "5e652aa6e01670abc8a59cda",
    index: 8,
    guid: "7a8beb9c-9e84-42d0-bb31-f73b247ba373",
    isActive: false,
    balance: "$3,570.48",
    picture: "http://placehold.it/32x32",
    age: 33,
    eyeColor: "blue",
    name: "Richardson Erickson",
    gender: "male",
    company: "ZILLACOM",
    email: "richardsonerickson@zillacom.com",
    phone: "+1 (912) 579-2968",
    address: "503 Dwight Street, Edinburg, Texas, 3249",
    about:
      "Labore non incididunt enim eiusmod aliqua officia ullamco adipisicing voluptate adipisicing. Eiusmod dolor ad tempor occaecat dolore occaecat officia minim officia in excepteur non in voluptate. Exercitation exercitation laboris nulla ad id irure Lorem aliquip velit labore nostrud ex eiusmod excepteur. Veniam et fugiat ipsum qui velit deserunt eiusmod quis fugiat adipisicing. Labore voluptate consectetur magna sit est ullamco irure cupidatat consectetur ullamco. Eiusmod commodo tempor mollit exercitation velit labore ipsum.\r\n",
    registered: "2014-02-15T02:46:50 -02:00",
    latitude: -1.073143,
    longitude: 84.572358,
    tags: [
      "elit",
      "nulla",
      "adipisicing",
      "fugiat",
      "qui",
      "amet",
      "voluptate",
    ],
    friends: [
      {
        id: 0,
        name: "Mays Francis",
      },
      {
        id: 1,
        name: "Kerr Wolfe",
      },
      {
        id: 2,
        name: "Pearlie Willis",
      },
    ],
  },
  {
    _id: "5e652aa6310c610a545c467e",
    index: 9,
    guid: "52a293e1-2acf-4c79-bf22-e1ca9fe62762",
    isActive: false,
    balance: "$3,893.12",
    picture: "http://placehold.it/32x32",
    age: 25,
    eyeColor: "brown",
    name: "Harriet Barnes",
    gender: "female",
    company: "TASMANIA",
    email: "harrietbarnes@tasmania.com",
    phone: "+1 (868) 513-3593",
    address: "894 Degraw Street, Unionville, Massachusetts, 5905",
    about:
      "Nulla commodo id dolor minim sint est Lorem ut aliqua velit qui et sit ut. Minim quis sit reprehenderit sit ipsum elit fugiat est exercitation dolor. Adipisicing aute nulla ullamco aliqua aute elit. Enim irure eiusmod cillum reprehenderit. Voluptate reprehenderit nostrud veniam eu et qui elit deserunt ad est ea. In sint tempor pariatur fugiat magna mollit excepteur ea commodo consequat.\r\n",
    registered: "2014-11-27T09:12:20 -02:00",
    latitude: -17.574855,
    longitude: -88.004737,
    tags: ["ad", "proident", "cupidatat", "nisi", "nisi", "ea", "proident"],
    friends: [
      {
        id: 0,
        name: "Conway Reilly",
      },
      {
        id: 1,
        name: "Livingston Alvarado",
      },
      {
        id: 2,
        name: "Pace Woodard",
      },
    ],
  },
  {
    _id: "5e652aa684a4286a926a35be",
    index: 10,
    guid: "b32c193c-1011-4231-af3d-0332e1caa087",
    isActive: true,
    balance: "$2,026.32",
    picture: "http://placehold.it/32x32",
    age: 23,
    eyeColor: "brown",
    name: "Morin Christensen",
    gender: "male",
    company: "ISOTRONIC",
    email: "morinchristensen@isotronic.com",
    phone: "+1 (935) 406-2797",
    address: "423 Cook Street, Caron, District Of Columbia, 9715",
    about:
      "Enim ad sunt dolor exercitation duis velit et id aute elit officia. Pariatur laboris exercitation ullamco ipsum commodo non excepteur. Amet cupidatat aute ipsum eu est mollit ea. Veniam dolor laborum magna officia ut nulla occaecat aliqua irure. Quis velit proident exercitation irure dolor.\r\n",
    registered: "2014-04-10T12:12:10 -03:00",
    latitude: -61.755351,
    longitude: -168.009704,
    tags: ["consectetur", "fugiat", "do", "veniam", "elit", "tempor", "qui"],
    friends: [
      {
        id: 0,
        name: "Marie Hawkins",
      },
      {
        id: 1,
        name: "Buchanan Alston",
      },
      {
        id: 2,
        name: "Alvarado Adams",
      },
    ],
  },
  {
    _id: "5e652aa6fb34c68462a97fe9",
    index: 11,
    guid: "7dd83a10-d09a-4c34-b7ab-2bca9dbeda18",
    isActive: true,
    balance: "$1,903.83",
    picture: "http://placehold.it/32x32",
    age: 29,
    eyeColor: "green",
    name: "Bernice Dickson",
    gender: "female",
    company: "BULLZONE",
    email: "bernicedickson@bullzone.com",
    phone: "+1 (950) 471-3058",
    address: "879 Denton Place, Westboro, Arizona, 3638",
    about:
      "Minim magna nisi sint dolor fugiat mollit aute qui. Ullamco voluptate deserunt magna exercitation reprehenderit cupidatat non reprehenderit ex cillum. Do deserunt ex consequat minim Lorem in consequat. Id in do anim Lorem velit aliquip nisi sunt adipisicing elit minim eu ex. Lorem amet consectetur et dolor magna eu aute elit quis eiusmod.\r\n",
    registered: "2016-02-18T09:16:34 -02:00",
    latitude: 32.61059,
    longitude: 112.024336,
    tags: ["ex", "do", "amet", "ex", "laborum", "in", "labore"],
    friends: [
      {
        id: 0,
        name: "Mueller Waters",
      },
      {
        id: 1,
        name: "Shirley Rios",
      },
      {
        id: 2,
        name: "Magdalena Fleming",
      },
    ],
  },
  {
    _id: "5e652aa60cbf2b40e7f64e58",
    index: 12,
    guid: "e269ffa7-ee63-4614-beac-4da3b8316d67",
    isActive: false,
    balance: "$3,960.88",
    picture: "http://placehold.it/32x32",
    age: 22,
    eyeColor: "blue",
    name: "Gonzalez Wheeler",
    gender: "male",
    company: "MOREGANIC",
    email: "gonzalezwheeler@moreganic.com",
    phone: "+1 (837) 448-3136",
    address: "652 Russell Street, Statenville, Tennessee, 3939",
    about:
      "Cillum duis reprehenderit ipsum quis aliqua dolor cillum ullamco nisi qui labore et consectetur. Cillum qui laboris Lorem nulla sint culpa ad quis commodo. Velit irure aute voluptate deserunt adipisicing.\r\n",
    registered: "2014-09-19T04:18:26 -03:00",
    latitude: -59.717771,
    longitude: 110.816644,
    tags: ["ex", "non", "nostrud", "Lorem", "tempor", "sit", "commodo"],
    friends: [
      {
        id: 0,
        name: "Howe Quinn",
      },
      {
        id: 1,
        name: "Rose Trujillo",
      },
      {
        id: 2,
        name: "Roy Justice",
      },
    ],
  },
  {
    _id: "5e652aa6d99be4ee07a5d34f",
    index: 13,
    guid: "5ac9cc7e-d39c-40bb-b6fc-19e9bc5f44e6",
    isActive: false,
    balance: "$3,730.68",
    picture: "http://placehold.it/32x32",
    age: 20,
    eyeColor: "brown",
    name: "Beasley Avila",
    gender: "male",
    company: "EARTHMARK",
    email: "beasleyavila@earthmark.com",
    phone: "+1 (812) 550-3217",
    address: "395 Seaview Court, Sunwest, Virgin Islands, 8804",
    about:
      "Exercitation reprehenderit pariatur do incididunt anim esse id qui irure dolor est ut est aliquip. Amet anim labore laboris labore est exercitation pariatur laborum reprehenderit proident. Velit ut quis ex laborum aute duis.\r\n",
    registered: "2016-01-20T08:21:14 -02:00",
    latitude: -44.154861,
    longitude: -54.722159,
    tags: ["do", "qui", "exercitation", "minim", "commodo", "et", "anim"],
    friends: [
      {
        id: 0,
        name: "Juanita Oconnor",
      },
      {
        id: 1,
        name: "Janis Cline",
      },
      {
        id: 2,
        name: "Meredith Boyd",
      },
    ],
  },
  {
    _id: "5e652aa659a9911f63e6e218",
    index: 14,
    guid: "591dc369-5583-45d1-8e8e-03908a59a59c",
    isActive: false,
    balance: "$1,371.28",
    picture: "http://placehold.it/32x32",
    age: 33,
    eyeColor: "brown",
    name: "Garner Rivas",
    gender: "male",
    company: "EMPIRICA",
    email: "garnerrivas@empirica.com",
    phone: "+1 (808) 522-3505",
    address: "170 Henry Street, Keyport, Kansas, 8925",
    about:
      "Lorem ea sint officia Lorem incididunt enim ea eu et adipisicing. Labore et fugiat qui cillum. Eu esse veniam enim amet dolor labore et et commodo reprehenderit irure fugiat enim aliquip. Occaecat do ad excepteur sunt cupidatat minim cupidatat officia occaecat dolore et aliqua duis consectetur.\r\n",
    registered: "2016-09-23T12:22:16 -03:00",
    latitude: 41.053996,
    longitude: -118.933789,
    tags: ["laborum", "veniam", "enim", "magna", "amet", "nulla", "dolor"],
    friends: [
      {
        id: 0,
        name: "Faye Crane",
      },
      {
        id: 1,
        name: "Kennedy Schneider",
      },
      {
        id: 2,
        name: "Murray Clemons",
      },
    ],
  },
  {
    _id: "5e652aa6f3429802e92fcebe",
    index: 15,
    guid: "5b3752ad-1529-4893-b63d-2b994355fa7e",
    isActive: true,
    balance: "$2,563.90",
    picture: "http://placehold.it/32x32",
    age: 30,
    eyeColor: "green",
    name: "Dotson Chavez",
    gender: "male",
    company: "PHARMACON",
    email: "dotsonchavez@pharmacon.com",
    phone: "+1 (968) 442-2504",
    address: "269 Autumn Avenue, Woodlands, Maryland, 4852",
    about:
      "Fugiat sit cupidatat proident pariatur consectetur. Aliquip et fugiat irure in ea fugiat sint. Duis qui deserunt non non.\r\n",
    registered: "2019-11-27T04:47:21 -03:00",
    latitude: 42.597019,
    longitude: -146.934485,
    tags: ["adipisicing", "sint", "aliqua", "elit", "cillum", "ea", "nisi"],
    friends: [
      {
        id: 0,
        name: "Charlene Knox",
      },
      {
        id: 1,
        name: "Jarvis Travis",
      },
      {
        id: 2,
        name: "Robbins Brennan",
      },
    ],
  },
  {
    _id: "5e652aa6483b2328c5af14a1",
    index: 16,
    guid: "f7172ec2-385b-426d-86bb-3fcab8384053",
    isActive: true,
    balance: "$3,508.68",
    picture: "http://placehold.it/32x32",
    age: 23,
    eyeColor: "green",
    name: "Faith Mcgee",
    gender: "female",
    company: "MANGELICA",
    email: "faithmcgee@mangelica.com",
    phone: "+1 (886) 485-2914",
    address: "575 Bergen Court, Harborton, Wyoming, 2029",
    about:
      "Cupidatat nulla magna quis laboris aliquip cupidatat elit ipsum. Sint aute incididunt ullamco non exercitation. Sint reprehenderit qui Lorem culpa ad qui ipsum. Sit adipisicing ad mollit commodo eu labore veniam laborum.\r\n",
    registered: "2015-09-15T10:50:00 -03:00",
    latitude: 14.946777,
    longitude: 14.025736,
    tags: ["in", "reprehenderit", "laborum", "cillum", "non", "in", "aliqua"],
    friends: [
      {
        id: 0,
        name: "Emily Soto",
      },
      {
        id: 1,
        name: "Jasmine Osborn",
      },
      {
        id: 2,
        name: "Jolene Oneil",
      },
    ],
  },
  {
    _id: "5e652aa60875b58090c2bdc1",
    index: 17,
    guid: "51b6a1c0-b0d9-4683-8608-1c0c8b5e3fd9",
    isActive: true,
    balance: "$3,720.72",
    picture: "http://placehold.it/32x32",
    age: 36,
    eyeColor: "green",
    name: "Hillary Cote",
    gender: "female",
    company: "DAISU",
    email: "hillarycote@daisu.com",
    phone: "+1 (840) 426-2769",
    address: "471 Otsego Street, Greenbush, Puerto Rico, 905",
    about:
      "Culpa exercitation qui sit non enim eu mollit. Qui aliquip duis consectetur amet nisi. Duis commodo adipisicing nulla commodo labore consequat laborum deserunt culpa sint nisi tempor dolore.\r\n",
    registered: "2016-12-25T11:36:30 -03:00",
    latitude: 19.128477,
    longitude: 95.822803,
    tags: ["ullamco", "nostrud", "minim", "laboris", "proident", "elit", "ex"],
    friends: [
      {
        id: 0,
        name: "Etta Cotton",
      },
      {
        id: 1,
        name: "Deena Barton",
      },
      {
        id: 2,
        name: "Mcintyre Bender",
      },
    ],
  },
  {
    _id: "5e652aa625dd9fedff2aa553",
    index: 18,
    guid: "a3c19c2a-b7a9-44c3-806e-2ebef8fc2206",
    isActive: true,
    balance: "$2,973.79",
    picture: "http://placehold.it/32x32",
    age: 37,
    eyeColor: "brown",
    name: "Knowles Sargent",
    gender: "male",
    company: "CENTREE",
    email: "knowlessargent@centree.com",
    phone: "+1 (973) 560-2573",
    address: "964 Elm Avenue, Berlin, Marshall Islands, 7611",
    about:
      "Veniam consequat Lorem commodo sint ipsum mollit cupidatat ullamco ullamco adipisicing magna. Sit deserunt aute do esse nisi aliqua ea minim laborum nisi elit anim exercitation minim. Proident tempor eu laboris est duis culpa. Cillum dolore voluptate eu cupidatat do dolor consequat ut nisi. Officia est ut qui aute duis eiusmod sit dolor sit reprehenderit proident id.\r\n",
    registered: "2017-08-19T05:12:27 -03:00",
    latitude: 10.573019,
    longitude: 112.973862,
    tags: ["aliquip", "quis", "labore", "do", "enim", "non", "adipisicing"],
    friends: [
      {
        id: 0,
        name: "Ellen Dunlap",
      },
      {
        id: 1,
        name: "Lily Wilson",
      },
      {
        id: 2,
        name: "Hall Patterson",
      },
    ],
  },
  {
    _id: "5e652aa62b89bf17581362d8",
    index: 19,
    guid: "f2e43303-d73a-4125-aa11-23ca1f2e8896",
    isActive: true,
    balance: "$3,492.18",
    picture: "http://placehold.it/32x32",
    age: 40,
    eyeColor: "blue",
    name: "Maribel Bartlett",
    gender: "female",
    company: "PYRAMAX",
    email: "maribelbartlett@pyramax.com",
    phone: "+1 (840) 569-3885",
    address: "783 Wolcott Street, Boomer, New Hampshire, 3885",
    about:
      "Aute mollit incididunt cupidatat duis cupidatat velit officia et fugiat laboris ea velit mollit. Velit consequat nisi laborum adipisicing. Eu excepteur cillum ex ex anim exercitation eiusmod sit anim consectetur minim. Quis anim amet in dolor. Laborum occaecat exercitation consequat minim qui ex sint reprehenderit enim adipisicing officia voluptate. Deserunt ullamco excepteur commodo est ad aliquip. Aute ullamco sunt occaecat officia fugiat ullamco.\r\n",
    registered: "2018-04-18T08:07:08 -03:00",
    latitude: -84.786252,
    longitude: 159.569476,
    tags: ["Lorem", "esse", "fugiat", "aliqua", "sit", "culpa", "elit"],
    friends: [
      {
        id: 0,
        name: "Blair Barker",
      },
      {
        id: 1,
        name: "Dionne Donaldson",
      },
      {
        id: 2,
        name: "Lott Neal",
      },
    ],
  },
  {
    _id: "5e652aa6ca46450c0058b0da",
    index: 20,
    guid: "ffc705e9-afb6-4719-b62a-1e1d466e1246",
    isActive: false,
    balance: "$2,653.83",
    picture: "http://placehold.it/32x32",
    age: 28,
    eyeColor: "blue",
    name: "Guadalupe Wong",
    gender: "female",
    company: "NETAGY",
    email: "guadalupewong@netagy.com",
    phone: "+1 (875) 428-3812",
    address: "257 Kent Street, Lund, Palau, 1093",
    about:
      "Dolor ex incididunt excepteur voluptate cupidatat est. Proident sit esse sunt ad occaecat officia Lorem. Mollit Lorem proident ea fugiat excepteur eu labore anim nostrud commodo ea. Commodo laboris enim duis ad nulla nostrud nisi est enim deserunt fugiat amet.\r\n",
    registered: "2017-01-25T10:35:29 -03:00",
    latitude: -63.78226,
    longitude: -133.547597,
    tags: ["eu", "excepteur", "tempor", "cupidatat", "esse", "velit", "irure"],
    friends: [
      {
        id: 0,
        name: "Little Wilder",
      },
      {
        id: 1,
        name: "Clarice Dodson",
      },
      {
        id: 2,
        name: "Lillian Little",
      },
    ],
  },
  {
    _id: "5e652aa613bafdacbd4163be",
    index: 21,
    guid: "d0cb7bcc-b517-4d2e-b99e-9352574026d6",
    isActive: false,
    balance: "$2,522.13",
    picture: "http://placehold.it/32x32",
    age: 27,
    eyeColor: "brown",
    name: "Griffin Glenn",
    gender: "male",
    company: "EQUITOX",
    email: "griffinglenn@equitox.com",
    phone: "+1 (999) 422-2826",
    address: "644 Madison Street, Mulino, New Jersey, 6776",
    about:
      "Duis aliquip non cillum commodo do id sint adipisicing proident eiusmod ullamco exercitation et. Incididunt do laborum aliquip ullamco. Aliqua laborum labore aute do enim irure commodo.\r\n",
    registered: "2017-12-28T07:24:49 -03:00",
    latitude: -48.341825,
    longitude: -60.469833,
    tags: ["dolore", "eiusmod", "qui", "duis", "commodo", "amet", "veniam"],
    friends: [
      {
        id: 0,
        name: "Addie Pacheco",
      },
      {
        id: 1,
        name: "Hernandez Delgado",
      },
      {
        id: 2,
        name: "Becker Roy",
      },
    ],
  },
  {
    _id: "5e652aa6b850b57672fd0f07",
    index: 22,
    guid: "75cf2691-2023-4b61-b8c1-1a7b6e1ecad3",
    isActive: true,
    balance: "$3,366.93",
    picture: "http://placehold.it/32x32",
    age: 36,
    eyeColor: "brown",
    name: "Dina Winters",
    gender: "female",
    company: "CIRCUM",
    email: "dinawinters@circum.com",
    phone: "+1 (850) 482-3471",
    address: "911 Lott Avenue, Conway, Delaware, 8050",
    about:
      "Aliqua minim ullamco velit reprehenderit non sit id nulla dolor veniam aliquip. Et dolor in ea qui irure cillum in nisi. Mollit irure irure id tempor quis consectetur deserunt mollit. Consequat laboris do est proident irure elit ut quis cupidatat laborum. Tempor sint proident incididunt est minim ex veniam velit sunt. Aliquip esse quis cillum est pariatur incididunt sit sit ex.\r\n",
    registered: "2016-06-23T01:08:44 -03:00",
    latitude: -36.550758,
    longitude: -71.338761,
    tags: [
      "exercitation",
      "deserunt",
      "dolore",
      "sit",
      "do",
      "laboris",
      "aliqua",
    ],
    friends: [
      {
        id: 0,
        name: "Harriett Schmidt",
      },
      {
        id: 1,
        name: "Mejia Wells",
      },
      {
        id: 2,
        name: "Tammie Pace",
      },
    ],
  },
  {
    _id: "5e652aa64e3c446eb168c72d",
    index: 23,
    guid: "71eb79e5-c361-4e63-b39c-da359e1c7d90",
    isActive: true,
    balance: "$1,800.84",
    picture: "http://placehold.it/32x32",
    age: 20,
    eyeColor: "brown",
    name: "Lenore Garner",
    gender: "female",
    company: "COLUMELLA",
    email: "lenoregarner@columella.com",
    phone: "+1 (954) 582-3993",
    address: "308 Arion Place, Siglerville, Washington, 4925",
    about:
      "Occaecat velit enim cillum in amet sunt. Ad officia elit reprehenderit minim ea tempor sit aliquip deserunt. Adipisicing quis adipisicing tempor est amet eu. Proident veniam sint dolore ipsum non. Veniam consectetur fugiat dolor est culpa Lorem consequat irure occaecat culpa. Non adipisicing reprehenderit id est labore. Ad ex excepteur dolore deserunt velit cillum in non.\r\n",
    registered: "2019-02-17T07:27:15 -03:00",
    latitude: -80.300331,
    longitude: 175.267045,
    tags: [
      "nostrud",
      "labore",
      "duis",
      "pariatur",
      "proident",
      "occaecat",
      "sint",
    ],
    friends: [
      {
        id: 0,
        name: "Craft Frank",
      },
      {
        id: 1,
        name: "Mcknight Bishop",
      },
      {
        id: 2,
        name: "Jodi Reyes",
      },
    ],
  },
  {
    _id: "5e652aa6f0e67d49162bb42e",
    index: 24,
    guid: "26915491-55e5-42f5-8a67-42204289d828",
    isActive: false,
    balance: "$3,141.05",
    picture: "http://placehold.it/32x32",
    age: 23,
    eyeColor: "brown",
    name: "Sloan Whitaker",
    gender: "male",
    company: "DIGIAL",
    email: "sloanwhitaker@digial.com",
    phone: "+1 (900) 526-2952",
    address: "198 Division Place, Dowling, Alaska, 7077",
    about:
      "Aute consequat eu exercitation laboris commodo Lorem proident nostrud mollit fugiat exercitation amet. Tempor dolore incididunt ad Lorem deserunt culpa dolore cillum aliquip. Officia non mollit excepteur Lorem enim elit. Officia elit cillum dolor qui et aute duis aliquip consectetur tempor.\r\n",
    registered: "2019-12-09T11:00:35 -03:00",
    latitude: -87.032275,
    longitude: -64.708331,
    tags: [
      "aliqua",
      "nisi",
      "nulla",
      "culpa",
      "dolore",
      "excepteur",
      "proident",
    ],
    friends: [
      {
        id: 0,
        name: "Pratt Frederick",
      },
      {
        id: 1,
        name: "Sweeney Rhodes",
      },
      {
        id: 2,
        name: "Shepherd Green",
      },
    ],
  },
  {
    _id: "5e652aa6668fa09b97b21d96",
    index: 25,
    guid: "d1afe0bd-10ea-4698-b067-d383cea497f1",
    isActive: false,
    balance: "$2,053.66",
    picture: "http://placehold.it/32x32",
    age: 23,
    eyeColor: "green",
    name: "Carrillo Spencer",
    gender: "male",
    company: "SNOWPOKE",
    email: "carrillospencer@snowpoke.com",
    phone: "+1 (890) 549-3091",
    address: "933 Hooper Street, Hinsdale, Pennsylvania, 143",
    about:
      "Duis amet laborum consequat occaecat occaecat voluptate aute magna proident excepteur duis tempor. Amet aliquip ea eu consectetur ipsum qui aliqua. Deserunt eu do veniam consequat dolore culpa minim exercitation sint ut. Do aliquip proident velit irure deserunt incididunt nulla pariatur voluptate laborum ut enim.\r\n",
    registered: "2018-09-13T05:25:33 -03:00",
    latitude: -5.297365,
    longitude: 20.28695,
    tags: ["ut", "consectetur", "veniam", "laborum", "do", "ipsum", "culpa"],
    friends: [
      {
        id: 0,
        name: "Andrea Jensen",
      },
      {
        id: 1,
        name: "Wilda Rodgers",
      },
      {
        id: 2,
        name: "Lupe Jenkins",
      },
    ],
  },
  {
    _id: "5e652aa646a7f0cb7702bff0",
    index: 26,
    guid: "de556c06-140a-498a-b495-fcb8b9f26500",
    isActive: true,
    balance: "$1,258.50",
    picture: "http://placehold.it/32x32",
    age: 35,
    eyeColor: "blue",
    name: "Cooper Monroe",
    gender: "male",
    company: "ZINCA",
    email: "coopermonroe@zinca.com",
    phone: "+1 (908) 539-2185",
    address: "502 Halleck Street, Kidder, West Virginia, 5245",
    about:
      "Amet consectetur cillum non nisi commodo proident ullamco sunt eu mollit eu cillum aute ex. Aute qui non sit labore cillum nostrud labore fugiat dolor sint ea. Excepteur nostrud et tempor aliquip. Nulla voluptate eiusmod eiusmod veniam.\r\n",
    registered: "2018-07-25T05:42:16 -03:00",
    latitude: -60.216936,
    longitude: -124.801569,
    tags: [
      "amet",
      "proident",
      "do",
      "occaecat",
      "exercitation",
      "deserunt",
      "sint",
    ],
    friends: [
      {
        id: 0,
        name: "Cassie Black",
      },
      {
        id: 1,
        name: "Crosby Montoya",
      },
      {
        id: 2,
        name: "Alta Pittman",
      },
    ],
  },
  {
    _id: "5e652aa6a4ee346b32d37b57",
    index: 27,
    guid: "70e52cad-d205-42c9-8b34-0f865c1631b0",
    isActive: false,
    balance: "$1,596.05",
    picture: "http://placehold.it/32x32",
    age: 39,
    eyeColor: "green",
    name: "Mckay Murray",
    gender: "male",
    company: "PLASMOX",
    email: "mckaymurray@plasmox.com",
    phone: "+1 (809) 473-3295",
    address: "576 Mill Avenue, Henrietta, South Dakota, 4608",
    about:
      "Voluptate nisi ea consequat pariatur veniam ipsum est pariatur anim aliqua voluptate voluptate. Eu eu pariatur Lorem cupidatat proident deserunt consequat ex in. Anim laboris commodo velit in incididunt dolor aliqua culpa Lorem elit sit laborum. Reprehenderit enim nulla consequat incididunt laborum.\r\n",
    registered: "2014-10-06T01:46:17 -03:00",
    latitude: -38.304396,
    longitude: 145.985843,
    tags: ["ea", "aliqua", "officia", "nulla", "tempor", "ex", "enim"],
    friends: [
      {
        id: 0,
        name: "Maura Hansen",
      },
      {
        id: 1,
        name: "Katelyn Marsh",
      },
      {
        id: 2,
        name: "Jamie Albert",
      },
    ],
  },
  {
    _id: "5e652aa631ac9f5d0a8ea682",
    index: 28,
    guid: "73cc5e2f-6c0b-4b57-ac76-544bdb8ee8aa",
    isActive: true,
    balance: "$3,019.10",
    picture: "http://placehold.it/32x32",
    age: 35,
    eyeColor: "green",
    name: "Sonya Barron",
    gender: "female",
    company: "EXOBLUE",
    email: "sonyabarron@exoblue.com",
    phone: "+1 (912) 532-2594",
    address: "469 Linden Boulevard, Drummond, Northern Mariana Islands, 8184",
    about:
      "Fugiat sint quis adipisicing dolor labore ad dolore eiusmod duis aute nostrud labore veniam do. Dolore laboris laboris laboris et ut pariatur eu id. Exercitation et dolore dolor proident nulla deserunt anim duis anim non qui reprehenderit aliqua.\r\n",
    registered: "2015-07-31T12:08:16 -03:00",
    latitude: -56.13545,
    longitude: -61.715736,
    tags: [
      "aliqua",
      "labore",
      "ullamco",
      "culpa",
      "dolor",
      "exercitation",
      "sit",
    ],
    friends: [
      {
        id: 0,
        name: "Elliott Holloway",
      },
      {
        id: 1,
        name: "Miranda Allison",
      },
      {
        id: 2,
        name: "Tonia Fields",
      },
    ],
  },
];

console.log(data);
 let founded = null;

// founded = data.find(item =>

//   item.eyeColor=="blue"

// )
// console.log(founded)

// founded = data.findIndex(item => item._id=="5e652aa6baec2fe6fea7ed2c")
// console.log(founded)

// let newArry = ["alptuğ", "alican", "muhammet", "ali", "sefa", 1, 2, 3, 4, 5];
// founded = newArry.indexOf((1,2))
// console.log(founded)

founded = data.filter(item =>{

   return`${item.age>30} ${item.eyeColor="blue"}`
} )
console.log(founded)

// founded = data.map((item,index) => {
// console.log(index)
// return {
//  isim : item.name,
//  yas:  item.age,
//  cinsiyet :item.gender,
// }
// }).filter(item => item.yas<30)
// console.log(founded)

/////////////////////////////////////////////////////////////////////////////////////DOM///////////////////////////////////////////////////////////////////////////////
// console.log(document.location.pathname);
// console.log(document.URL);
// console.log(document.baseURI);

// console.log(document.head);
// console.log(document.body);
// document.body.style.backgroundColor = "blue";

// let title = document.getElementById('title')

// console.log(title)
// console.log(title.innerHTML="merhaba experilabs")

// let link = document.querySelector("ul#list>li>a")
// console.log(link)

// let link2 = document.querySelector("#linktest")
// console.log(link2.innerHTML)
// link2.style.color="red";
// link2.classList.add('btn')

// let classa= document.querySelector("ul.test.deneme")
//  console.log(classa.innerHTML="Ayşe")

